apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gpu-v1
  region: ap-northeast-2

vpc:
  id: vpc-011ed6975f1c72790
  subnets:
    public:
      ap-northeast-2a: { id: subnet-054f9afb782fceef1 }
      ap-northeast-2c: { id: subnet-0921478b22fe6b19d}
    private:
      ap-northeast-2a: { id: subnet-0eb32c43acaaa38ee }
      ap-northeast-2c: { id: subnet-071a900bf8f16453c }
    
managedNodeGroups:
- name: cpu-ng
  instanceType: c5.xlarge
  minSize: 2
  maxSize: 10
  desiredCapacity: 2
  privateNetworking: true
  tags:
    nodegroup-role: worker
- name: gpu-ng2
  instanceType: p2.xlarge
  minSize: 3
  maxSize: 10
  desiredCapacity: 3
  privateNetworking: true
  labels: {accelerator: nvidia-gpu}
  tags:
    nodegroup-role: worker