# gpu-hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-gpu
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    # name: <DEPLOYMENT_NAME>
    name: <DEPLOYMENT_NAME>
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        # name: dcgm-exporter
        name: dcgm-exporter
      metricName: DCGM_FI_DEV_GPU_UTIL
      targetValue: 30