---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inf-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inf-api
  template:
    metadata:
      labels:
        app: inf-api
    spec:
      containers:
        - name: inf-api
          image: 681747700094.dkr.ecr.ap-northeast-2.amazonaws.com/dev-oct-productapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1024Mi"
              # cpu: 1
            limits:
              nvidia.com/gpu: 1
          env:
          - name: env
            value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: inf-api
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/product/ping"
spec:
  selector:
    app: inf-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inf-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inf-api
  minReplicas: 3
  maxReplicas: 300
  targetCPUUtilizationPercentage: 20
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "inf-api-v3-alb-ingress"
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: inf-api-v3
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=30
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:681747700094:certificate/ad3b4737-a573-4e0c-ba16-3b4305138fd9
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/tags: env=dev
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '16'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '15'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
spec:
  rules:
  - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: "inf-api"
                port:
                  number: 8080
