apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
  name: vision-api
spec:
  groups:
  - name: gpu_scaling
    rules:
    # - record: gpu_avg
    - alert: vision-api_scaling
      expr: ceil(avg(avg_over_time(DCGM_FI_DEV_GPU_UTIL{exported_container="vision-api"}[60s]))) > 30
      for: 5s
      labels:
        namespace: default
        deployment: vision-api
    - alert: vision-api_scaling_avg
      expr: DCGM_FI_DEV_GPU_UTIL_AVG{exported_container="vision-api"}[60s]) > 30
      for: 5s
      labels:
        namespace: default
        deployment: vision-api
    - alert: vision-api_scaling_min
      expr: DCGM_FI_DEV_GPU_UTIL_MIN{exported_container="vision-api"}[60s]) < 10
      for: 5s
      labels:
        namespace: default
        deployment: vision-api
    - alert: vision-api_scaling_max
      expr: DCGM_FI_DEV_GPU_UTIL_MAX{exported_container="vision-api"}[60s]) > 60
      for: 5s
      labels:
        namespace: default
        deployment: vision-api