# eksctl create cluster -f chart-p-cluster.yaml --without-nodegroup
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gpu-chart-p
  region: ap-northeast-2

vpc:
  id: vpc-011ed6975f1c72790
  subnets:
    public:
      ap-northeast-2a: { id: subnet-054f9afb782fceef1 }
      ap-northeast-2c: { id: subnet-0921478b22fe6b19d}
    private:
      ap-northeast-2a: { id: subnet-0eb32c43acaaa38ee }
      ap-northeast-2c: { id: subnet-071a900bf8f16453c }