prometheus:
    # kube-prometheus-stack chart
    url: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local
    port: 9090
rules:
  default: true
  custom:
    - seriesQuery: 'DCGM_FI_DEV_GPU_UTIL'
      name:
        as: "DCGM_FI_DEV_GPU_UTIL_AVG"
      metricsQuery: ceil(avg_over_time(<<.Series>>{<<.LabelMatchers>>}[60s]))
      resources:
        overrides:
          exported_container: {resource: "service"}
          exported_namespace: {resource: "namespace"}
          exported_pod: {resource: "pod"}
    # # - seriesQuery: 'DCGM_FI_DEV_GPU_UTIL{exported_namespace="default"}'
    # - seriesQuery: 'DCGM_FI_DEV_GPU_UTIL'
    #   name:
    #     as: "DCGM_FI_DEV_GPU_UTIL_AVG"
    #   metricsQuery: ceil(avg_over_time(<<.Series>>{<<.LabelMatchers>>}[60s]))
    #   resources:
    #     overrides:
    #       exported_container: {resource: "service"}
    #       exported_namespace: {resource: "namespace"}
    #       exported_pod: {resource: "pod"}