apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: vision-api
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: vision-api
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://172.20.23.19:9090
      metricName: DCGM_FI_DEV_GPU_UTIL
      threshold: '30'
      query: sum(rate(http_requests_total{deployment="my-deployment"}[2m]))

# https://docs.microsoft.com/ko-kr/azure/azure-functions/functions-kubernetes-keda

# 
# pollingInterval: 30  
#   cooldownPeriod:  300 
#   minReplicaCount: 0   
#   maxReplicaCount: 100 
#   triggers: