# 
# eksctl create cluster -f gpu-cluster.yaml --without-nodegroup
# 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gpu-demo
  region: us-east-1

vpc:
  id: <vpc-id>
  subnets:
    public:
      us-east-1a: { id: <public-subnet1> }
      us-east-1b: { id: <public-subnet2> }
    private:
      us-east-1a: { id: <private-subnet1> }
      us-east-1b: { id: <private-subnet2> }